services:
  app:
    command: sh -c "npm install & npm run start:dev"
    build: .
    volumes:
      - .:/app
    ports:
      - 3000:3000
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: test
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
